// Adapter for the WebAssembly module generated from the `wasm/` crate
// (timbrei-dsp-wasm), which is itself a thin shell over the verified DSP in the
// lemi backend. The compiled artifact lives in `./wasm-pkg/` and is versioned
// (see `npm run build:wasm`), so the Vite build on Netlify does not need the
// Rust toolchain.
//
// Exposes the same shape as `verifiedBiquad.ts` (VBiquadCoeffs) so the
// `biquad.ts` facade can switch backends transparently.

import type { VBiquadCoeffs } from './verifiedBiquad';
// Static import of the glue generated by wasm-pack (--target web). The `init`
// default export downloads and instantiates the .wasm; the functions are
// synchronous afterwards.
import init, {
  peaking as wasmPeaking,
  low_shelf as wasmLowShelf,
  high_shelf as wasmHighShelf,
} from './wasm-pkg/timbrei_dsp';

let ready = false;

/** Instantiates the WASM module. Idempotent; rejects if the .wasm fails to load. */
export async function initWasm(): Promise<void> {
  if (ready) return;
  await init();
  ready = true;
}

export const isReady = (): boolean => ready;

const toCoeffs = (a: Float64Array | number[]): VBiquadCoeffs => ({
  b0: a[0], b1: a[1], b2: a[2], a1: a[3], a2: a[4],
});

export function peaking(f0: number, fs: number, q: number, gainDb: number): VBiquadCoeffs {
  return toCoeffs(wasmPeaking(f0, fs, q, gainDb));
}

export function lowShelf(f0: number, fs: number, s: number, gainDb: number): VBiquadCoeffs {
  return toCoeffs(wasmLowShelf(f0, fs, s, gainDb));
}

export function highShelf(f0: number, fs: number, s: number, gainDb: number): VBiquadCoeffs {
  return toCoeffs(wasmHighShelf(f0, fs, s, gainDb));
}
